[package]
name = "test_contract"
version = "0.1.0"
authors = ["Pactus blockchain <info@pactus.org>"]
edition = "2024"

[dependencies]
kelk = { version = "0.4.0", git = "https://github.com/pactus-project/kelk"}
minicbor = { version = "1.0", features = ["derive"] }
blake2 = "0.10"

[lib]
name = "test_contract"
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = false
