[package]
description = "Tanour"
name = "tanour"
version = "0.2.0"
authors = ["Pactus blockchain <info@pactus.org>"]
edition = "2024"

[dependencies]
byteorder = "1.5"
log = "0.4"
wasmer = { version = "6.0", default-features = false, features = [
    "wat",
    "singlepass",
] }
wasmer-middlewares = "6.0"
thiserror = "2.0"
hex = "0.4"
mockall = "0.13"

[dev-dependencies]
minicbor = { version = "2.1", features = ["std"] }
simple_logger = "5.0"
wat = "1"
test_contract = { path = "../test-contract" }
blake2 = "0.10"
hex-literal = "1.0"
quickcheck = "1"
quickcheck_macros = "1"
rand = "0.9"

[lib]
path = "src/lib.rs"
