on: [pull_request]
name: Formatting

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # We can delete this part in future
    - name: Installing nightly
      run: rustup default nightly --component rustfmt clippy

    - name: fmt check
      run: cargo +nightly fmt --all -- --check

    - name: Clippy check
      run: cargo +nightly clippy --all-targets --all-features -- -D warnings