on: [pull_request]
name: Formatting

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Installing nightly
      run: rustup toolchain install nightly --component rustfmt clippy

    - name: fmt check
      run: cargo +nightly fmt --all -- --check

    - name: Clippy check
      run: cargo +nightly clippy --all-targets --all-features -- -D warnings