on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

name: Testing

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # We can delete this part in future
    - name: Installing nightly
      run: rustup default nightly

    - name: Unit tests
      run: cargo +nightly test
