on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

name: Testing

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Installing nightly and wasm32 target
    - name: Installing nightly
      run: rustup toolchain install nightly --target wasm32-unknown-unknown

    # Compining test-contract
    - name: Compiling test-contract
      run: |
        cd test-contract
        cargo +nightly build --target wasm32-unknown-unknown --release -Z unstable-options --out-dir ./wasm

    - name: Unit tests
      run: cargo +nightly test
